const RIGHT_WALL = 250;
const LEFT_WALL = 50;
const FIELD_WIDTH = 15;
const FIELD_HEIGHT = 20;
const FLOOR = 400;
const BLOCK_SIZE = 20;
const NEXT_BLOCK_LEFT = 400;
const NEXT_BLOCK_TOP = 100;
var objectData;
var currentBlocks;
var nextBlocks;
var oldBlocks;
var graphics;
var leftKey;
var	rightKey;
var	upKey;
var	downKey;
var	spaceKey;
var block;
var score = 0;
var timer = 0;
var speed = 50;
var nextBlockNum;
var highScore = 0;
var newBlock;
var nextBlock;